In [11]:
import pandas as pd
import csv
import matplotlib.pyplot as plt
import requests
import pandas as pd
from config2 import api_key
from pandas_function import make_df
import time

In [12]:
#Opening and reading a city list by population and cleaning the dataframe. This list will be used to create the list of cities we will be running our analysis
file_one = "Population_List.csv"
file_one_df = pd.read_csv(file_one, encoding="ISO-8859-1")
newDF = file_one_df[["NAME","STNAME","POPESTIMATE2018"]]

In [13]:
# Data is a mix of cities and state. So we need to remove all State Level Information
state_list = newDF["STNAME"].unique()
state_list = newDF["STNAME"].unique()
cond = newDF['NAME'].isin(state_list) == True
newDF.drop(newDF[cond].index, inplace = True)

In [14]:
#Function to Clean city data
def City_Cleaner(df,value):
    Bad_City_DF = df[df['NAME'].str.contains(value)]
    Bad_City_List = Bad_City_DF['NAME']
    cond = df['NAME'].isin(Bad_City_List) == True
    df.drop(df[cond].index, inplace = True)

In [15]:
#All the variables that were removed from the data to remove duplicates and also to clean the data such that it can be inputed into the main function
City_Cleaner(newDF,"County")
City_Cleaner(newDF,"(pt.)")
City_Cleaner(newDF,"(balance)")
City_Cleaner(newDF,"metropolitan government")
City_Cleaner(newDF,"Balance of")
City_Cleaner(newDF,"Hempstead")
City_Cleaner(newDF,"Washington")
City_Cleaner(newDF,"Parish")

In [16]:
# Sort data by population largest to smallest
final_DF = newDF.sort_values(by=['POPESTIMATE2018'], ascending=False)

In [17]:
# Remove city duplicates
final_DF = final_DF.drop_duplicates(subset ="NAME", keep="first")

In [18]:
#Remove all terms such as city or town
final_DF = final_DF.head(50)

final_DF['NAME'] = final_DF['NAME'].str.replace(' city', '')
final_DF['NAME'] = final_DF['NAME'].str.replace(' town', '')
final_DF

                   NAME          STNAME  POPESTIMATE2018
46586          New York        New York          8398748
3090        Los Angeles      California          3990456
8172            Chicago        Illinois          2705994
71683           Houston           Texas          2325502
1608            Phoenix         Arizona          1660272
66100      Philadelphia    Pennsylvania          1584138
72159       San Antonio           Texas          1532233
3750          San Diego      California          1425976
71459            Dallas           Texas          1345047
3820           San Jose      California          1030119
71240            Austin           Texas           964254
5204       Jacksonville         Florida           903889
71562        Fort Worth           Texas           895008
54088          Columbus            Ohio           892533
3222      San Francisco      California           883305
15886      Indianapolis         Indiana           876862
49731         Charlotte  North Carolina           872498
76193           Seattle      Washington           744955
3991             Denver        Colorado           716492
28785            Boston   Massachusetts           694583
71526           El Paso           Texas           682669
28991           Detroit        Michigan           672662
61051          Portland          Oregon           653115
71093           Memphis       Tennessee           650618
59900     Oklahoma City        Oklahoma           649021
43983         Las Vegas          Nevada           644644
27964         Baltimore        Maryland           602495
77550         Milwaukee       Wisconsin           592025
45938       Albuquerque      New Mexico           560218
1636             Tucson         Arizona           545975
3403             Fresno      California           530093
1500               Mesa         Arizona           508958
3209         Sacramento      California           508529
6023            Atlanta         Georgia           498044
39240       Kansas City        Missouri           491918
49197        Brookhaven        New York           482436
3975   Colorado Springs        Colorado           472688
5275              Miami         Florida           470914
50031           Raleigh  North Carolina           469298
42320             Omaha        Nebraska           468262
3085         Long Beach      California           467354
75511    Virginia Beach        Virginia           450189
3342            Oakland      California           429082
33076       Minneapolis       Minnesota           425403
60035             Tulsa        Oklahoma           400669
71232         Arlington           Texas           398112
5625              Tampa         Florida           392890
26791       New Orleans       Louisiana           391006
24927           Wichita          Kansas           389255
55736         Cleveland            Ohio           383793

In [19]:
#Saving the population list DF
final_DF.to_csv("US_pop_df.csv")

In [20]:
#Creating List of our main variables to be used to create Main Data Frame
City_List = list(final_DF["NAME"])
State_List = list(final_DF["STNAME"])
Output_List = []

In [23]:
#Creating a list of lists in the form of (City, State, Country), since this is the primary way our DF API function inputs parameter
for i in range(len(City_List)-1):
    TempList = [City_List[i],State_List[i], "USA"]
    Output_List.append(TempList)

In [24]:
#The API would time out very easily when we try to pull too much in a short period of time. So we broke the work into pieces to call.
#Creating Variable list to hold results
Output_DF_Holder =[]
DF_List =[]

In [25]:
#Creating the smaller groups
for i in range(0,10):
    Output_List_Temp=Output_List[5*i:5*i+5]
    Output_DF_Holder.append(Output_List_Temp)

In [78]:
#running each 5 cities seperately to ensure the pull does not time out
a = make_df(Output_DF_Holder[0])

In [80]:
b= make_df(Output_DF_Holder[1])

In [81]:
c= make_df(Output_DF_Holder[2])

In [126]:
d= make_df(Output_DF_Holder[3])

In [131]:
e= make_df(Output_DF_Holder[4])

In [132]:
f= make_df(Output_DF_Holder[5])

In [134]:
g= make_df(Output_DF_Holder[6])

In [135]:
h= make_df(Output_DF_Holder[7])

In [154]:
i= make_df(Output_DF_Holder[8])

In [155]:
j= make_df(Output_DF_Holder[9])

In [157]:
frames = [a, b, c,d,e,f,g,h,i,j]
result_df = pd.concat(frames)

In [158]:
result_df

,City,State,Country,Longitude,Latitude,Air Quality,Temperature,Humidity,Pressure,Wind Speed,Date
0,New York,New York,USA,-73.928596,40.694401,26,21,73,1018,4.60,2019-10-07
1,Los Angeles,California,USA,-118.241700,34.066900,33,27,42,1012,2.60,2019-10-07
2,Chicago,Illinois,USA,-87.723900,41.913600,16,18,34,1021,3.60,2019-10-07
3,Houston,Texas,USA,-95.326100,29.901100,62,25,69,1016,6.20,2019-10-07
4,Phoenix,Arizona,USA,-112.066299,33.560299,51,35,15,1011,4.10,2019-10-07
0,Philadelphia,Pennsylvania,USA,-75.080833,39.991389,8,22,69,1018,3.10,2019-10-07
1,San Antonio,Texas,USA,-98.332838,29.352910,35,28,42,1017,6.70,2019-10-07
2,San Diego,California,USA,-117.149651,32.701492,29,25,69,1012,5.70,2019-10-07
3,Dallas,Texas,USA,-96.860000,32.820000,1,25,31,1020,5.10,2019-10-07
4,San Jose,California,USA,-121.849892,37.338202,19,30,22,1013,3.60,2019-10-07
0,Austin,Texas,USA,-97.760002,30.354200,25,25,44,1019,4.10,2019-10-07
1,Jacksonville,Florida,USA,-81.586900,30.475800,24,22,100,1014,3.60,2019-10-07
2,Fort Worth,Texas,USA,-97.341400,32.759200,0,25,29,1021,5.70,2019-10-07
3,Columbus,Ohio,USA,-82.994404,40.002734,27,15,63,1022,2.10,2019-10-07
4,San Francisco,California,USA,-122.397800,37.765800,25,26,34,1013,4.60,2019-10-07
0,Indianapolis,Indiana,USA,-86.214700,39.788900,14,14,87,1022,1.13,2019-10-08
1,Charlotte,North Carolina,USA,-80.783100,35.241100,8,22,64,1017,3.10,2019-10-08
2,Seattle,Washington,USA,-122.308628,47.568236,13,15,77,1011,6.20,2019-10-08
3,Denver,Colorado,USA,-105.005230,39.779400,5,22,6,1019,4.10,2019-10-08
4,Boston,Massachusetts,USA,-71.054200,42.363100,5,20,64,1019,5.70,2019-10-08
0,El Paso,Texas,USA,-106.402802,31.746700,33,23,33,1021,4.60,2019-10-08
1,Detroit,Michigan,USA,-83.068900,42.323100,11,13,54,1021,2.93,2019-10-08
2,Portland,Oregon,USA,-122.635895,45.525980,49,18,63,1016,3.60,2019-10-08
3,Memphis,Tennessee,USA,-89.850220,35.151588,14,16,63,1021,4.10,2019-10-08
4,Oklahoma City,Oklahoma,USA,-97.577674,35.502968,21,18,37,1022,2.10,2019-10-08
0,Las Vegas,Nevada,USA,-115.113900,36.163900,41,28,6,1014,3.10,2019-10-08
1,Baltimore,Maryland,USA,-76.296700,39.410000,34,21,69,1019,2.60,2019-10-08
2,Milwaukee,Wisconsin,USA,-87.912500,43.061100,20,12,66,1022,1.45,2019-10-08
3,Albuquerque,New Mexico,USA,-106.651901,35.018600,26,21,40,1023,4.60,2019-10-08
4,Tucson,Arizona,USA,-110.982200,32.295300,13,34,21,1013,2.10,2019-10-08
0,Fresno,California,USA,-119.773206,36.785378,27,30,18,1012,3.04,2019-10-08
1,Mesa,Arizona,USA,-111.865100,33.410500,4,35,15,1010,2.39,2019-10-08
2,Sacramento,California,USA,-121.368007,38.613804,21,30,16,1012,2.60,2019-10-08
3,Atlanta,Georgia,USA,-84.357800,33.720600,24,22,64,1017,3.60,2019-10-08
4,Kansas City,Missouri,USA,-94.570602,39.104698,15,16,52,1022,1.52,2019-10-08
0,Brookhaven,New York,USA,-72.915380,40.779270,5,20,77,1019,4.10,2019-10-07
1,Colorado Springs,Colorado,USA,-104.828600,38.848000,28,16,12,1022,5.10,2019-10-08
2,Miami,Florida,USA,-80.215600,25.794700,21,24,88,1010,3.10,2019-10-08
3,Raleigh,North Carolina,USA,-78.574203,35.856098,12,22,78,1017,0.24,2019-10-08
4,Omaha,Nebraska,USA,-95.973100,41.247400,4,18,40,1020,2.10,2019-10-08
0,Long Beach,California,USA,-118.175278,33.792221,22,27,33,1012,6.20,2019-10-08
1,Virginia Beach,Virginia,USA,-75.985914,36.859521,5,22,83,1018,3.10,2019-10-08
2,Oakland,California,USA,-122.282402,37.814800,25,26,28,1013,4.60,2019-10-08
3,Minneapolis,Minnesota,USA,-93.258100,44.953600,22,13,58,1018,1.50,2019-10-08
4,Tulsa,Oklahoma,USA,-95.976402,36.206699,21,17,45,1022,1.38,2019-10-08
0,Arlington,Texas,USA,-97.088600,32.655800,2,23,36,1020,3.60,2019-10-08
1,Tampa,Florida,USA,-82.538300,27.892800,17,24,88,1010,4.10,2019-10-08
2,New Orleans,Louisiana,USA,-90.101400,29.993300,41,26,74,1015,4.60,2019-10-08
3,Wichita,Kansas,USA,-97.297200,37.659700,11,18,42,1022,2.10,2019-10-08

In [161]:
#Saving DF to be used to charting
result_df.to_csv("LargestUSCitiesDF.csv")