In [75]:
import csv
import matplotlib.pyplot as plt
import requests
import pandas as pd
from config2 import api_key
from pprint import pprint

In [100]:
def make_df(city_list):
    
    dict_list = []
    
    for c in range(0, len(city_list)):
        
        citi = city_list[c][0]
        state = city_list[c][1]
        country = city_list[c][2]

        url = f"https://api.airvisual.com/v2/city?city={citi}&state={state}&country={country}&key="

        query_url = url + api_key

        response = requests.get(query_url).json()

        city = response['data']['city']
        state = response['data']['state']
        country = response['data']['country']
        temperature = response['data']['current']['weather']['tp']
        air_qual = response['data']['current']['pollution']['aqius']
        humidity = response['data']['current']['weather']['hu']
        pressure = response['data']['current']['weather']['pr']
        wind_speed = response['data']['current']['weather']['ws']
        time = response['data']['current']['weather']['ts']

        data_dict = {'City' : city, 'State' : state, 'Country' : country, 'Air Quality' : air_qual, 'Temperature' : temperature,
             'Humidity': humidity, 'Pressure' : pressure, 'Wind Speed' : wind_speed, 'Time' : time}
        dict_list.append(data_dict)
    dataframe = pd.DataFrame(dict_list)
    return dataframe

#This is where our opportunity to loop into our cities.
#Each city in the list must be formatted as [city, state, country]
city_list = [['Asheville', 'North Carolina', 'USA'], ['Charlotte', 'North Carolina', 'USA'], 
             ['Wilmington', 'North Carolina', 'USA'], ['Raleigh', 'North Carolina', 'USA'], 
             ['Los Angeles', 'California', 'USA']]

make_df(city_list)

,City,State,Country,Air Quality,Temperature,Humidity,Pressure,Wind Speed,Time
0,Asheville,North Carolina,USA,61,22,78,1021,3.10,2019-10-03T01:00:00.000Z
1,Charlotte,North Carolina,USA,79,26,58,1015,1.50,2019-10-03T01:00:00.000Z
2,Wilmington,North Carolina,USA,55,24,78,1015,1.50,2019-10-03T01:00:00.000Z
3,Raleigh,North Carolina,USA,88,26,100,1014,1.87,2019-10-03T01:00:00.000Z
4,Los Angeles,California,USA,17,22,46,1012,2.60,2019-10-03T01:00:00.000Z